#include "warpgate/hnsw_backend.hpp"
#include "warpgate/distance.hpp"
#include "warpgate/parallel.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <limits>
#include <queue>
#include <stdexcept>
#include <unordered_set>
namespace warpgate {
namespace {
template<class T> void write_pod(std::ostream& out,const T&v){out.write(reinterpret_cast<const char*>(&v),sizeof(T));if(!out)throw std::runtime_error("failed to write HNSW index");}
template<class T> T read_pod(std::istream& in){T v{};in.read(reinterpret_cast<char*>(&v),sizeof(T));if(!in)throw std::runtime_error("failed to read HNSW index");return v;}
constexpr std::array<char,8> kMagic{'W','G','H','N','S','W','0','1'};
}
HnswBackend::HnswBackend(std::vector<float>dataset,std::size_t rows,std::size_t dim,HnswConfig config):dataset_(std::move(dataset)),rows_(rows),dim_(dim),config_(config),rng_(config.seed){if(rows_==0||dim_==0||dataset_.size()!=rows_*dim_)throw std::invalid_argument("dataset shape does not match rows * dim");if(config_.m<2)throw std::invalid_argument("HNSW m must be >= 2");config_.ef_construction=std::max(config_.ef_construction,config_.m);config_.ef_search=std::max<std::size_t>(config_.ef_search,1);nodes_.reserve(rows_);for(std::size_t id=0;id<rows_;++id)insert_node(id);}
std::string_view HnswBackend::name()const noexcept{return "hnsw-cpu";}
std::size_t HnswBackend::preferred_max_batch()const noexcept{return 128;}
std::span<const float> HnswBackend::vector_at(std::size_t id)const{return {dataset_.data()+id*dim_,dim_};}
float HnswBackend::distance_to(std::span<const float>q,std::size_t id)const{return vector_distance(q,vector_at(id),config_.metric);}
int HnswBackend::sample_level(){std::uniform_real_distribution<double>u(std::numeric_limits<double>::min(),1.0);return static_cast<int>(-std::log(u(rng_))/std::log(static_cast<double>(config_.m)));}
std::size_t HnswBackend::greedy_at_level(std::span<const float>q,std::size_t entry,int level)const{std::size_t cur=entry;float best=distance_to(q,cur);bool improved=true;while(improved){improved=false;if(level>nodes_[cur].level)break;for(auto n:nodes_[cur].links[static_cast<std::size_t>(level)]){float d=distance_to(q,n);if(d<best){best=d;cur=n;improved=true;}}}return cur;}
std::vector<HnswBackend::Candidate> HnswBackend::search_layer(std::span<const float>q,std::size_t entry,std::size_t ef,int level)const{struct Min{bool operator()(const Candidate&a,const Candidate&b)const{return a.distance>b.distance;}};struct Max{bool operator()(const Candidate&a,const Candidate&b)const{return a.distance<b.distance;}};std::priority_queue<Candidate,std::vector<Candidate>,Min>cand;std::priority_queue<Candidate,std::vector<Candidate>,Max>best;std::unordered_set<std::size_t>visited;visited.reserve(ef*8+16);Candidate start{entry,distance_to(q,entry)};cand.push(start);best.push(start);visited.insert(entry);while(!cand.empty()){auto cur=cand.top();if(best.size()>=ef&&cur.distance>best.top().distance)break;cand.pop();if(level>nodes_[cur.id].level)continue;for(auto n:nodes_[cur.id].links[static_cast<std::size_t>(level)]){if(!visited.insert(n).second)continue;Candidate next{n,distance_to(q,n)};if(best.size()<ef||next.distance<best.top().distance){cand.push(next);best.push(next);if(best.size()>ef)best.pop();}}}std::vector<Candidate>out;out.reserve(best.size());while(!best.empty()){out.push_back(best.top());best.pop();}std::sort(out.begin(),out.end(),[](const Candidate&a,const Candidate&b){return a.distance<b.distance;});return out;}
void HnswBackend::prune(std::size_t node,int level){auto&links=nodes_[node].links[static_cast<std::size_t>(level)];if(links.size()<=config_.m)return;auto base=vector_at(node);std::sort(links.begin(),links.end(),[&](std::size_t a,std::size_t b){return vector_distance(base,vector_at(a),config_.metric)<vector_distance(base,vector_at(b),config_.metric);});links.resize(config_.m);}
void HnswBackend::connect_bidirectional(std::size_t a,std::size_t b,int level){auto&la=nodes_[a].links[static_cast<std::size_t>(level)];auto&lb=nodes_[b].links[static_cast<std::size_t>(level)];if(std::find(la.begin(),la.end(),b)==la.end())la.push_back(b);if(std::find(lb.begin(),lb.end(),a)==lb.end())lb.push_back(a);prune(a,level);prune(b,level);}
void HnswBackend::insert_node(std::size_t id){int level=sample_level();nodes_.push_back(Node{level,std::vector<std::vector<std::size_t>>(static_cast<std::size_t>(level+1))});if(id==0){entry_point_=0;max_level_=level;return;}auto q=vector_at(id);std::size_t entry=entry_point_;for(int l=max_level_;l>level;--l)entry=greedy_at_level(q,entry,l);for(int l=std::min(level,max_level_);l>=0;--l){auto candidates=search_layer(q,entry,config_.ef_construction,l);auto count=std::min(config_.m,candidates.size());for(std::size_t i=0;i<count;++i)connect_bidirectional(id,candidates[i].id,l);if(!candidates.empty())entry=candidates.front().id;}if(level>max_level_){entry_point_=id;max_level_=level;}}
SearchResult HnswBackend::search_one(const SearchQuery&q)const{if(q.vector.size()!=dim_)throw std::invalid_argument("query dimension mismatch");auto query=std::span<const float>(q.vector.data(),q.vector.size());std::size_t entry=entry_point_;for(int l=max_level_;l>0;--l)entry=greedy_at_level(query,entry,l);auto candidates=search_layer(query,entry,std::max({config_.ef_search,q.top_k,std::size_t{1}}),0);auto k=std::min(q.top_k,candidates.size());SearchResult out;out.reserve(k);for(std::size_t i=0;i<k;++i)out.push_back({candidates[i].id,candidates[i].distance});return out;}
std::vector<SearchResult> HnswBackend::search(std::span<const SearchQuery>q){return parallel_query_map(q,config_.workers,[this](const SearchQuery&x){return search_one(x);});}
void HnswBackend::save(const std::string&path)const{std::ofstream out(path,std::ios::binary|std::ios::trunc);if(!out)throw std::runtime_error("cannot open HNSW index for writing");out.write(kMagic.data(),static_cast<std::streamsize>(kMagic.size()));const std::uint64_t rows=rows_,dim=dim_,m=config_.m,efc=config_.ef_construction,efs=config_.ef_search,entry=entry_point_,nodes=nodes_.size();const std::uint32_t seed=config_.seed,metric=static_cast<std::uint32_t>(config_.metric);const std::int32_t maxl=max_level_;write_pod(out,rows);write_pod(out,dim);write_pod(out,m);write_pod(out,efc);write_pod(out,efs);write_pod(out,seed);write_pod(out,metric);write_pod(out,entry);write_pod(out,maxl);write_pod(out,nodes);out.write(reinterpret_cast<const char*>(dataset_.data()),static_cast<std::streamsize>(dataset_.size()*sizeof(float)));if(!out)throw std::runtime_error("failed to write HNSW vectors");for(const auto&node:nodes_){const std::int32_t level=node.level;write_pod(out,level);for(const auto&layer:node.links){const std::uint64_t count=layer.size();write_pod(out,count);for(auto id:layer){const std::uint64_t x=id;write_pod(out,x);}}}}
HnswBackend HnswBackend::load(const std::string&path,std::size_t workers){std::ifstream in(path,std::ios::binary);if(!in)throw std::runtime_error("cannot open HNSW index for reading");std::array<char,8>magic{};in.read(magic.data(),static_cast<std::streamsize>(magic.size()));if(magic!=kMagic)throw std::runtime_error("unsupported HNSW index format");HnswBackend h(EmptyTag{});h.rows_=read_pod<std::uint64_t>(in);h.dim_=read_pod<std::uint64_t>(in);h.config_.m=read_pod<std::uint64_t>(in);h.config_.ef_construction=read_pod<std::uint64_t>(in);h.config_.ef_search=read_pod<std::uint64_t>(in);h.config_.seed=read_pod<std::uint32_t>(in);const auto metric=read_pod<std::uint32_t>(in);if(metric>1)throw std::runtime_error("invalid HNSW distance metric");h.config_.metric=static_cast<DistanceMetric>(metric);h.config_.workers=workers;h.entry_point_=read_pod<std::uint64_t>(in);h.max_level_=read_pod<std::int32_t>(in);const auto node_count=read_pod<std::uint64_t>(in);if(node_count!=h.rows_||h.rows_==0||h.dim_==0)throw std::runtime_error("invalid HNSW index dimensions");h.dataset_.resize(h.rows_*h.dim_);in.read(reinterpret_cast<char*>(h.dataset_.data()),static_cast<std::streamsize>(h.dataset_.size()*sizeof(float)));if(!in)throw std::runtime_error("truncated HNSW vector data");h.nodes_.reserve(h.rows_);for(std::size_t i=0;i<h.rows_;++i){int level=read_pod<std::int32_t>(in);if(level<0||level>1000)throw std::runtime_error("invalid HNSW node level");Node node{level,std::vector<std::vector<std::size_t>>(static_cast<std::size_t>(level+1))};for(auto&layer:node.links){auto count=read_pod<std::uint64_t>(in);if(count>h.rows_)throw std::runtime_error("invalid HNSW link count");layer.reserve(count);for(std::uint64_t j=0;j<count;++j){auto id=read_pod<std::uint64_t>(in);if(id>=h.rows_)throw std::runtime_error("invalid HNSW link id");layer.push_back(static_cast<std::size_t>(id));}}h.nodes_.push_back(std::move(node));}if(h.entry_point_>=h.rows_)throw std::runtime_error("invalid HNSW entry point");h.rng_.seed(h.config_.seed);return h;}
}
